
title: Sarah Berthelemy
description: Small household works, decorating and garden maintenance in and around Le Faouët, Le Saint, Guiscriff, Scaer, Gourin, Lanvenegen, Querrien and Priziac  
url: https://berthelemy.github.io
baseurl: /sarah.berthelemy.net

exclude:
 # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/